btoz-dev/agogo-pos-web-app

src/App.js
src/components/carts/CartProductionTotal.jsx
src/components/carts/cartsProduction/CartProduction.jsx
src/components/carts/cartsProduction/CartProduction.scss
src/components/carts/cartsProduction/OthersProduction.jsx
src/components/carts/cartsProduction/ProductionStore.jsx
src/components/navigations/FooterNavLeftProduction.jsx
src/components/production/Production.jsx
src/components/selection/Selection.css
src/components/selection/Selection.jsx

create page production

---

package-lock.json
package.json
src/components/booking/Booking.jsx
src/components/calcs/CalcNumeric.jsx
src/components/calcs/CalcNumericRefund.jsx
src/components/navigations/FooterNavRightBooking.jsx
src/components/order/DeleteBooking.jsx
src/components/order/EditBooking.jsx
src/components/order/EditBooking.scss
src/components/order/OrderBooking.jsx
src/components/order/OrderItem.jsx
src/components/order/TakeBooking.jsx
src/components/payments/Refund.jsx
src/components/reservation/Reservationtem.jsx
src/components/transaction/TransactionItem.jsx
src/components/transaction/TransactionItem.scss
src/components/users/UsersContainer.jsx
src/containers/CartsContainer.js

merger dgn mas anggi, fix kalkulasi transaksi, add fungsi pada pemesanan

merger dgn mas anggi, fix kalkulasi transaksi, add fungsi pada pemesanan

---

src/App.js
src/components/balances/InitialBalance.jsx
src/components/booking/Booking.jsx
src/components/carts/Cart.jsx
src/components/carts/CartBookingTotal.jsx
src/components/carts/RefundItem.jsx
src/components/carts/RefundItems.jsx
src/components/carts/cartsBooking/CartBooking.jsx
src/components/cashier/Cashier.jsx
src/components/logins/Login.jsx
src/components/modals/Modals.jsx
src/components/payments/Refund.jsx
src/components/payments/Refund.scss
src/components/payments/ReservationCheckout.jsx
src/components/reservation/ReservationItems.jsx
src/components/reservation/ReservationList.jsx
src/components/reservation/Reservationtem.jsx
src/components/selection/Selection.jsx
src/components/transaction/TransactionItem.jsx
src/components/transaction/TransactionItems.jsx
src/components/transaction/TransactionList.jsx
src/components/users/UserCard.jsx
src/components/users/UserList.jsx
src/containers/CartsContainer.js
src/containers/TransactionContainer.js

add role selection, fungsi judul order, hapus, fix bug

add role selection, fungsi judul order, hapus, fix bug

---

src/components/balances/InitialBalance.jsx
src/components/booking/Booking.jsx
src/components/carts/cartsProduction/CartProduction.jsx
src/components/cashier/Cashier.jsx
src/components/cashier/Cashier.scss
src/components/logins/Login.scss
src/components/modals/Modals.jsx
src/components/navigations/FooterNavLeft.jsx
src/components/order/DeleteBooking.jsx
src/components/order/EditBooking.jsx
src/components/order/OrderBooking.jsx
src/components/order/TakeBooking.jsx
src/components/payments/ReservationCheckout.jsx
src/components/production/Production.jsx
src/components/reservation/ReservationItems.jsx
src/components/reservation/ReservationList.jsx
src/components/transaction/TransactionItems.jsx
src/components/users/UserCard.jsx
src/components/users/UserList.jsx
src/containers/CartsContainer.js
src/containers/ModalsContainer.js
src/containers/TransactionContainer.js
src/index.js
src/sass/index.scss

fix issue produksi, fix kondisi tombol di kasir

 fix issue produksi, fix kondisi tombol di kasir

---

src/components/navigations/FooterNavLeft.jsx
src/components/payments/PaymentCheckout.jsx
src/components/users/UserList.jsx
src/containers/CartsContainer.js
src/containers/TransactionContainer.js

fix kondisi dalam pembayaran, modal sudah OK

 fix kondisi dalam pembayaran, modal sudah OK

---

src/components/calcs/CalcNumericRefund.jsx
src/components/carts/Cart.jsx
src/components/carts/CartBookingTotal.jsx
src/components/carts/CartTotal.jsx
src/components/carts/cartsBooking/CartBooking.jsx
src/components/carts/cartsProduction/CartProduction.jsx
src/components/carts/cartsProduction/OthersProduction.jsx
src/components/modals/Modals.jsx
src/components/navigations/FooterNavLeft.jsx
src/components/order/DeleteBooking.jsx
src/components/order/EditBooking.jsx
src/components/order/EditBooking.scss
src/components/order/OrderBooking.jsx
src/components/order/OrderBooking.scss
src/components/order/TakeBooking.jsx
src/components/payments/PaymentCheckout.jsx
src/components/payments/Refund.jsx
src/components/payments/ReservationCheckout.jsx
src/components/reservation/ReservationItem.jsx
src/components/reservation/ReservationItems.jsx
src/components/reservation/ReservationList.jsx
src/components/transaction/TransactionItems.jsx
src/components/transaction/TransactionList.jsx
src/containers/CartsContainer.js
src/containers/ModalsContainer.js

fix delete trx, reservation, form pemesanan, catatan produksi

fix delete trx, reservation, form pemesanan, catatan produksi

---

src/containers/CartsContainer.js

fix produksi

---

src/components/booking/Booking.jsx
src/components/selection/Selection.jsx
src/containers/CartsContainer.js
src/containers/ModalsContainer.js
src/containers/TransactionContainer.js
src/services/PostData.js

fix bugs pada produk kasir yang kadang menumpuk

fix bugs pada produk kasir yang kadang menumpuk

---

src/components/navigations/FooterNavLeft.jsx

hide qty barcode

---

src/components/booking/Booking.scss
src/components/order/EditBooking.jsx
src/components/order/EditBooking.scss
src/components/order/OrderBooking.jsx
src/components/order/OrderBooking.scss

fixing form pemesanan

---

src/App.js
src/components/carts/Cart.scss
src/components/carts/cartsProduction/CartProduction.jsx
src/components/carts/cartsProduction/CartProduction.scss
src/components/logins/Login.jsx
src/components/modals/Modal.scss
src/components/modals/Modals.jsx
src/components/order/OrderBooking.jsx
src/components/order/OrderBookingDelete.jsx
src/components/order/OrderBookingEdit.jsx
src/components/order/OrderBookingTake.jsx
src/components/reservation/ReservationList.jsx
src/components/transaction/TransactionList.jsx
src/containers/CartsContainer.js
src/index.js
src/sass/index.scss

fixing fullscreen modal

---

src/components/order/EditBooking.jsx
src/components/order/EditBooking.scss
src/components/order/OrderBooking.jsx
src/components/order/OrderBooking.scss

memperbaiki form pemesanan(ada yg kelupaan)

memperbaiki form pemesanan(ada yg kelupaan)

---

src/App.js
src/components/order/OrderBooking.jsx
src/containers/CartsContainer.js

fixing refund PS & TK
ID : https://app.clickup.com/t/zycdw

fixing refund PS & TK

---

src/components/carts/CartItem.jsx
src/components/carts/RefundItem.jsx
src/components/transaction/TransactionItems.jsx
src/containers/CartsContainer.js

ID: https://app.clickup.com/t/10pdgv

disable input qty saat refund

---

src/components/carts/CartItem.jsx
src/containers/CartsContainer.js

Fixing refund #10pdwz

---

src/components/reservation/ReservationItem.jsx
src/components/reservation/ReservationList.jsx
src/components/transaction/TransactionItem.jsx
src/components/transaction/TransactionItems.jsx
src/components/transaction/TransactionList.jsx

fixing trx list #109p1r

---

src/components/booking/Booking.jsx
src/components/carts/cartsProduction/CartProduction.jsx
src/components/carts/cartsProduction/CartProduction.scss
src/components/order/DeleteBooking.jsx
src/components/order/OrderBooking.jsx
src/containers/CartsContainer.js

fixing issue #109pzk #zy5qu #109pz3 pada modul produksi

fixing issue #109pzk #zy5qu #109pz3 pada modul produksi

---

src/components/carts/cartsProduction/CartProduction.jsx
src/components/carts/cartsProduction/CartProduction.scss
src/components/carts/cartsProduction/OthersProduction.jsx
src/containers/CartsContainer.js

fixing error produksi #10vdke

---

src/components/modals/Modals.jsx
src/components/order/OrderBooking.jsx
src/containers/CartsContainer.js

fixing #10vwp5
Produksi: Ubah placeholder "Jumlah Produksi" jd "Jumlah" pd window isian saat klik Jml Prod/Lain-lain

fixing #10vwp5

---

src/containers/CartsContainer.js

fixing production #w12uj #109px8
Fixing Isu2 Produksi

fixing production #w12uj #109px8

---

src/components/carts/CartTotal.jsx
src/components/logins/Login.jsx
src/components/modals/Modals.jsx
src/components/transaction/TransactionItem.jsx
src/containers/CartsContainer.js

fixing pemesanan #118nrb memperbaiki input uang muka

fixing pemesanan #118nrb memperbaiki input uang muka

---

src/components/order/DeleteBooking.jsx
src/components/order/EditBooking.jsx
src/components/order/OrderBooking.jsx
src/components/order/OrderBooking.scss
src/components/order/TakeBooking.jsx
src/components/payments/PaymentCheckout.jsx
src/components/payments/Refund.jsx
src/components/payments/ReservationCheckout.jsx
src/containers/CartsContainer.js

fixing date format #15k4k3

---

src/components/calcs/CalcNumericModal.jsx
src/components/calcs/CalcNumericModal.scss
src/components/carts/cartsProduction/OthersProduction.jsx
src/components/modals/Modals.jsx
src/components/order/EditBooking.scss
src/components/order/OrderBooking.scss
src/components/payments/PaymentCheckout.jsx
src/components/payments/Refund.jsx
src/containers/CartsContainer.js

fix issue #15keyr #15keyj

---

.vscode/settings.json
package-lock.json
src/components/carts/CartBookingTotal.jsx
src/components/carts/CartTotal.jsx
src/components/carts/cartsProduction/CartProduction.jsx
src/components/modals/Modals.jsx
src/components/order/TakeBooking.jsx
src/components/payments/PaymentCheckout.jsx
src/components/reservation/ReservationItem.jsx
src/containers/CartsContainer.js

fix #17qrn4 #17qrpa #17qrq7 #17rcg7 #17qrp1

fix #17qrn4 #17qrpa #17qrq7 #17rcg7 #17qrp1

---

src/containers/CartsContainer.js

fix #17rd1t

---

src/components/navigations/FooterNavRightBooking.jsx
src/components/payments/ReservationCheckout.jsx
src/containers/CartsContainer.js

fix #17qrpv

---

src/components/payments/ReservationCheckout.jsx
src/components/selection/Selection.jsx
src/containers/CartsContainer.js

fix #19grgr

---

src/components/order/DeleteBooking.jsx
src/components/order/OrderItem.jsx
src/components/payments/ReservationCheckout.jsx
src/components/reservation/ReservationItem.jsx
src/components/transaction/TransactionItem.jsx

fixing  #15k4k3

---

src/components/balances/InitialBalance.jsx
src/components/logins/Login.jsx
src/components/modals/Modals.jsx
src/components/order/DeleteBooking.jsx
src/components/order/EditBooking.jsx
src/components/order/OrderBooking.jsx
src/components/order/OrderBooking.scss
src/components/order/TakeBooking.jsx
src/components/payments/Refund.jsx
src/components/payments/ReservationCheckout.jsx

fix #v8w6k

---

src/App.js
src/components/balances/InitialBalance.jsx
src/components/logins/Login.jsx
src/components/modals/Modal.scss
src/components/modals/Modals.jsx
src/components/order/DeleteBooking.jsx
src/components/order/EditBooking.jsx
src/components/order/OrderBooking.jsx
src/components/order/TakeBooking.jsx
src/components/payments/Refund.jsx
src/components/payments/ReservationCheckout.jsx
src/components/print/kasirOrder.jsx
src/components/print/kasirOrder.scss
src/components/products/ProductItems.jsx
src/components/selection/Selection.jsx
src/containers/CartsContainer.js

#19kex6 #19mpvj

---

src/components/booking/Booking.jsx
src/components/calcs/CalcNumericKas.jsx
src/components/logins/Login.jsx
src/components/modals/Modals.jsx
src/components/navigations/FooterNavRightBooking.jsx
src/components/navigations/FooterNavRightProduction.jsx
src/components/order/DeleteBooking.jsx
src/components/order/EditBooking.jsx
src/components/order/OrderBooking.jsx
src/components/order/OrderBookingDelete.jsx
src/components/order/OrderBookingEdit.jsx
src/components/order/OrderBookingTake.jsx
src/components/order/TakeBooking.jsx
src/components/payments/PaymentCheckout.jsx
src/components/payments/Refund.jsx
src/components/payments/ReservationCheckout.jsx
src/components/production/Production.jsx
src/components/transaction/TransactionList.jsx
src/containers/CartsContainer.js

fix #19knxu dan beberapa minor

fix #19knxu dan beberapa minor

---

src/App.js
src/components/carts/CartItem.jsx
src/components/cashier/Cashier.jsx
src/components/logins/Login.jsx
src/components/modals/Modals.jsx
src/components/order/DeleteBooking.jsx
src/components/order/EditBooking.jsx
src/components/order/OrderBooking.jsx
src/components/order/TakeBooking.jsx
src/components/print/kasirOrder.scss
src/components/print/pemesananOrder.jsx
src/containers/CartsContainer.js

fix #19q8d9 #19q783

---

src/components/balances/InitialBalance.jsx
src/components/carts/CartItem.jsx
src/containers/CartsContainer.js

fix #19mpvj & improve #19q783
